version: 2
multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-production:
        dependency-type: "production"
        patterns:
          - "*"
      npm-development:
        dependency-type: "development"
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/apps/web"
    patterns:
      - "*"
    multi-ecosystem-group: "infrastructure"
