#!/usr/bin/env bash

set -euo pipefail

REMOTE_NAME=${REMOTE_NAME:-origin}
HEAD_BRANCH=${HEAD_BRANCH:-staging}
BASE_BRANCH=${BASE_BRANCH:-main}
DRY_RUN=${DRY_RUN:-0}
UPDATE_EXISTING_PR=${UPDATE_EXISTING_PR:-1}
PROMOTION_DATE=${PROMOTION_DATE:-$(date +%F)}
PROMOTION_PR_TITLE=${PROMOTION_PR_TITLE:-Release: $HEAD_BRANCH -> $BASE_BRANCH ($PROMOTION_DATE)}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

csv_to_lines() {
  local csv="$1"
  local item
  local -a values=()

  if [ -z "$csv" ]; then
    return 0
  fi

  IFS=',' read -r -a values <<< "$csv"
  for item in "${values[@]}"; do
    item="$(trim "$item")"
    if [ -n "$item" ]; then
      printf '%s\n' "$item"
    fi
  done
}

resolve_repo() {
  if [ -n "${GH_REPO:-}" ]; then
    printf '%s\n' "$GH_REPO"
    return 0
  fi

  local remote_url
  remote_url="$(git config --get "remote.${REMOTE_NAME}.url" || true)"
  if [ -z "$remote_url" ]; then
    echo "GH_REPO is not set and remote ${REMOTE_NAME} has no URL." >&2
    exit 1
  fi

  local repo
  repo="$(gh repo view --json nameWithOwner --jq '.nameWithOwner' 2>/dev/null || true)"
  if [ -z "$repo" ]; then
    repo="$(printf '%s\n' "$remote_url" | sed -E 's#(git@github.com:|https://github.com/|ssh://git@github.com/)##; s#\.git$##')"
  fi
  if ! printf '%s\n' "$repo" | grep -Eq '^[^/]+/[^/]+$'; then
    echo "Could not infer GitHub repository from remote URL: $remote_url" >&2
    exit 1
  fi

  printf '%s\n' "$repo"
}

build_included_pr_lines() {
  local pr_number metadata number title author

  if [ "$#" -eq 0 ]; then
    printf '%s\n' "- No merged PRs were detected automatically."
    return 0
  fi

  for pr_number in "$@"; do
    if ! metadata="$(
      gh pr view "$pr_number" \
        --repo "$GH_REPO" \
        --json number,title,author \
        --jq '[.number, .title, (.author.login // "unknown")] | @tsv' 2>/dev/null
    )"; then
      printf 'Warning: skipping non-PR or failed lookup for #%s\n' "$pr_number" >&2
      continue
    fi
    if [ -z "$metadata" ]; then
      printf 'Warning: skipping empty metadata lookup for #%s\n' "$pr_number" >&2
      continue
    fi
    IFS=$'\t' read -r number title author <<< "$metadata"
    printf -- '- #%s: %s (@%s)\n' "$number" "$title" "$author"
  done
}

build_body() {
  local included_pr_lines="$1"
  local compare_url="https://github.com/$GH_REPO/compare/$BASE_BRANCH...$HEAD_BRANCH?expand=1"

  cat <<EOF
## Summary
Promotes \`$HEAD_BRANCH\` into \`$BASE_BRANCH\`.

- Source branch: \`$HEAD_BRANCH\`
- Target branch: \`$BASE_BRANCH\`
- Generated by \`npm run pr:promote\`

## Included PRs
$included_pr_lines

## Compare
- $compare_url
EOF
}

GH_REPO="$(resolve_repo)"
PROMOTION_PR_LABELS=${PROMOTION_PR_LABELS:-}
PROMOTION_PR_ASSIGNEES=${PROMOTION_PR_ASSIGNEES:-}
PROMOTION_PR_REVIEWERS=${PROMOTION_PR_REVIEWERS:-}

git fetch "$REMOTE_NAME" "$BASE_BRANCH" "$HEAD_BRANCH" --quiet

base_ref="${REMOTE_NAME}/${BASE_BRANCH}"
head_ref="${REMOTE_NAME}/${HEAD_BRANCH}"

if ! git rev-parse --verify "$base_ref" >/dev/null 2>&1; then
  echo "Base ref not found: $base_ref" >&2
  exit 1
fi

if ! git rev-parse --verify "$head_ref" >/dev/null 2>&1; then
  echo "Head ref not found: $head_ref" >&2
  exit 1
fi

existing_pr_row="$(
  gh pr list \
    --repo "$GH_REPO" \
    --state open \
    --base "$BASE_BRANCH" \
    --head "$HEAD_BRANCH" \
    --json number,url \
    --jq 'if length > 0 then .[0] | [(.number | tostring), .url] | @tsv else "" end'
)"

existing_pr_number=""
existing_pr_url=""
if [ -n "$existing_pr_row" ]; then
  IFS=$'\t' read -r existing_pr_number existing_pr_url <<< "$existing_pr_row"
fi

ahead_by="$(git rev-list --count "$base_ref..$head_ref")"
if [ "${ahead_by:-0}" -eq 0 ]; then
  if [ -n "$existing_pr_url" ]; then
    echo "No new commits to promote. Existing PR remains open: $existing_pr_url"
    exit 0
  fi

  echo "No commits to promote from $HEAD_BRANCH into $BASE_BRANCH."
  exit 0
fi

declare -a pr_numbers=()
while IFS= read -r pr_number; do
  if [ -n "$pr_number" ]; then
    pr_numbers+=("$pr_number")
  fi
done < <(
  git log --pretty=format:'%s' "$base_ref..$head_ref" |
    while IFS= read -r subject; do
      printf '%s\n' "$subject" | sed -nE 's/^Merge pull request #([0-9]+).*$/\1/p'
    done |
    awk '!seen[$0]++'
)

included_pr_lines="$(build_included_pr_lines "${pr_numbers[@]}")"
body="$(build_body "$included_pr_lines")"

declare -a label_values=()
declare -a assignee_values=()
declare -a reviewer_values=()

while IFS= read -r value; do
  label_values+=("$value")
done < <(csv_to_lines "$PROMOTION_PR_LABELS")

while IFS= read -r value; do
  assignee_values+=("$value")
done < <(csv_to_lines "$PROMOTION_PR_ASSIGNEES")

while IFS= read -r value; do
  reviewer_values+=("$value")
done < <(csv_to_lines "$PROMOTION_PR_REVIEWERS")

if [ "$DRY_RUN" = "1" ]; then
  if [ -n "$existing_pr_number" ] && [ "$UPDATE_EXISTING_PR" = "1" ]; then
    echo "DRY_RUN=1, skipping PR update."
    echo "Would update PR #$existing_pr_number: $existing_pr_url"
  elif [ -n "$existing_pr_number" ]; then
    echo "DRY_RUN=1, skipping PR update and creation."
    echo "Existing promotion PR found: $existing_pr_url"
    echo "UPDATE_EXISTING_PR=0, leaving the current PR unchanged."
  else
    echo "DRY_RUN=1, skipping PR creation."
    echo "Would create PR: $HEAD_BRANCH -> $BASE_BRANCH"
  fi
  echo "Title: $PROMOTION_PR_TITLE"
  printf 'Body:\n%s\n' "$body"
  printf 'Labels: %s\n' "${label_values[*]:-(none)}"
  printf 'Assignees: %s\n' "${assignee_values[*]:-(none)}"
  printf 'Reviewers: %s\n' "${reviewer_values[*]:-(none)}"
  exit 0
fi

if [ -n "$existing_pr_number" ] && [ "$UPDATE_EXISTING_PR" = "1" ]; then
  edit_args=(
    --repo "$GH_REPO"
    --title "$PROMOTION_PR_TITLE"
    --body "$body"
  )
  for label in "${label_values[@]}"; do
    edit_args+=(--add-label "$label")
  done
  for assignee in "${assignee_values[@]}"; do
    edit_args+=(--add-assignee "$assignee")
  done
  for reviewer in "${reviewer_values[@]}"; do
    edit_args+=(--add-reviewer "$reviewer")
  done
  gh pr edit "$existing_pr_number" "${edit_args[@]}"
  echo "Updated existing promotion PR: $existing_pr_url"
  exit 0
fi

if [ -n "$existing_pr_number" ]; then
  echo "Existing promotion PR found: $existing_pr_url"
  echo "UPDATE_EXISTING_PR=0, skipping update and creation."
  exit 0
fi

create_args=(
  --repo "$GH_REPO"
  --base "$BASE_BRANCH"
  --head "$HEAD_BRANCH"
  --title "$PROMOTION_PR_TITLE"
  --body "$body"
)

for label in "${label_values[@]}"; do
  create_args+=(--label "$label")
done

for assignee in "${assignee_values[@]}"; do
  create_args+=(--assignee "$assignee")
done

for reviewer in "${reviewer_values[@]}"; do
  create_args+=(--reviewer "$reviewer")
done

gh pr create "${create_args[@]}"
