codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  api:
    paths:
      - apps/api/src/
    carryforward: true
  web:
    paths:
      - apps/web/src/
    carryforward: true
