codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 75%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  api:
    paths:
      - apps/api/src/
  web:
    paths:
      - apps/web/src/
