codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    # after_n_builds: 2
    manual: false
    comment:
      layout: "reach,diff,flags,files"
      behavior: default
      require_changes: "false"

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%

flags:
  api:
    paths:
      - apps/api/src/
  web:
    paths:
      - apps/web/src/
