name = "openshelf-api"
main = "src/index.ts"
compatibility_date = "2026-02-28"

[[d1_databases]]
binding = "DB"
database_name = "openshelf-db"
database_id = "652de1e3-ee65-4733-98a7-8f93863e1a02"

[[r2_buckets]]
bucket_name = "openshelf-files"
binding = "BUCKET"